source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLDataSource_Example', :exclusive => true do
  pod "PLDataSource", :path => "../"
end

target 'PLDataSource_Tests', :exclusive => true do
  pod "PLDataSource", :path => "../"
  pod "OCMock", '~> 3.2'
  
end
